import type { Metadata } from "next";
import "./globals.css";
import { raleway } from "@/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={raleway.className}>
      <body className="bg-main text-white">{children}</body>
    </html>
  );
}
